# Numpy is used for calculation purposes and dealing with arrays and multi-dimensional arrays.

### This is basically used to play with a lot of data

### numpy is very fast dealing with calculations

In [3]:
import numpy as np

In [29]:
my_lst = [1,2,3,4,5]

### multi-dimensional arrays

In [12]:
arr = np.array(my_lst)
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
arr.shape

(5,)

In [16]:
my_lst2 = my_lst
my_lst3 = my_lst

In [19]:
arr = np.array([my_lst,my_lst2,my_lst3])

In [21]:
type(arr)

numpy.ndarray

In [22]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [23]:
arr.shape

(3, 5)

In [24]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

In [26]:
arr.reshape(15)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [27]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [28]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

### Slicing or indexing arrays

In [30]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [32]:
arr.reshape(15)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [40]:
arr.shape

(3, 5)

#### This is happening because arr.reshape just create a new copy of array and does not change existing array

In [68]:
arr2 = arr.reshape(15)

In [70]:
arr2.shape

(15,)

In [74]:
arr2 = np.array([1,2,3,4])

In [76]:
arr2[3]

4

In [78]:
arr2[1:3]

array([2, 3])

In [83]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [85]:
arr[0:2,0:3]

array([[1, 2, 3],
       [1, 2, 3]])

In [87]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [89]:
arr[1,1]

2

In [91]:
arr[1:,1:]

array([[2, 3, 4, 5],
       [2, 3, 4, 5]])

In [93]:
arr[1:,2:4]

array([[3, 4],
       [3, 4]])

In [95]:
arr[1,1:4]

array([2, 3, 4])

## Some built-in functions of numpy

In [98]:
arr2

array([11, 12, 13, 14])

In [100]:
arr=arr2

In [102]:
arr[2]=20

In [103]:
arr

array([11, 12, 20, 14])

In [104]:
arr2

array([11, 12, 20, 14])

In [105]:
### arr and arr2 is sharing same memory when we assign arr=arr2 hence as one of them will change other will also change.

In [106]:
### here we can use copy function to create a different memory address for new array

In [107]:
arr=arr2.copy()

In [109]:
arr

array([11, 12, 20, 14])

In [110]:
arr2

array([11, 12, 20, 14])

In [111]:
arr[3]=13

In [112]:
arr

array([11, 12, 20, 13])

In [113]:
arr2

array([11, 12, 20, 14])

In [114]:
## arange function takes three argument as start, end and step to create a one-dimensional array
one_d_arr = np.arange(1,10,1)

In [116]:
one_d_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
one_d_arr = np.arange(1,10,3)

In [118]:
one_d_arr

array([1, 4, 7])

In [123]:
## linspace is a function which takes three argument as start, end and number of parts do you want to create between start and end

In [124]:
lins = np.linspace(1,10,20)
lins

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [126]:
lins = np.linspace(0,1,100)
lins

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [127]:
## ones is a function which creates arrays containing same element which is one

In [130]:
ones_arr = np.ones((2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [155]:
ones_arr = np.ones(5,dtype=int)
ones_arr

array([1, 1, 1, 1, 1])

In [157]:
## random distribution
### random values array in between [0,1)
np.random.rand(3,3)

array([[0.23750505, 0.34774133, 0.33757618],
       [0.76916411, 0.08083418, 0.32400338],
       [0.09410946, 0.88059231, 0.58546321]])

In [159]:
## randn select random variable based on 'standard normal distribution'
np.random.randn(4,4)

array([[-0.19522511,  0.82924121,  0.90400088, -1.15926477],
       [ 0.45782263, -1.15195372,  0.5755274 , -0.01716189],
       [-0.14809841,  0.57438035,  0.56126267, -1.26734639],
       [-0.00661126, -1.05349597, -0.57288359,  0.08218733]])

In [161]:
## randint gives specific random values from specific set
np.random.randint(0,100,8)

array([29, 75, 76, 84, 55, 85, 93, 31])

In [163]:
## random_sample gives random number between 0 and 1
np.random.random_sample((2,3))

array([[0.49801689, 0.61167119, 0.13643902],
       [0.09276897, 0.16320901, 0.98433341]])

## Some operations on array

In [133]:
arr1 = np.arange(1,15)

In [134]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [135]:
arr1*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [136]:
arr1/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. ])

In [151]:
arr

array([11, 12, 20, 13])

In [150]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [147]:
arr2 = arr[arr>6].copy()
arr2

array([11, 12, 20, 13])

In [149]:
arr

array([11, 12, 20, 13])

In [154]:
arr = np.arange(1,16).reshape(3,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])